# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/xmac/Downloads/CLion-2018.2.4/clion-2018.2.4/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/xmac/Downloads/CLion-2018.2.4/clion-2018.2.4/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/xmac/storage/projects/cpp/udpserver

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/xmac/storage/projects/cpp/udpserver

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/xmac/Downloads/CLion-2018.2.4/clion-2018.2.4/bin/cmake/linux/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/xmac/Downloads/CLion-2018.2.4/clion-2018.2.4/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xmac/storage/projects/cpp/udpserver/CMakeFiles /home/xmac/storage/projects/cpp/udpserver/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xmac/storage/projects/cpp/udpserver/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named cli

# Build rule for target.
cli: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cli
.PHONY : cli

# fast build rule for target.
cli/fast:
	$(MAKE) -f src/intro/CMakeFiles/cli.dir/build.make src/intro/CMakeFiles/cli.dir/build
.PHONY : cli/fast

#=============================================================================
# Target rules for targets named byteorder

# Build rule for target.
byteorder: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 byteorder
.PHONY : byteorder

# fast build rule for target.
byteorder/fast:
	$(MAKE) -f src/intro/CMakeFiles/byteorder.dir/build.make src/intro/CMakeFiles/byteorder.dir/build
.PHONY : byteorder/fast

#=============================================================================
# Target rules for targets named srv

# Build rule for target.
srv: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 srv
.PHONY : srv

# fast build rule for target.
srv/fast:
	$(MAKE) -f src/intro/CMakeFiles/srv.dir/build.make src/intro/CMakeFiles/srv.dir/build
.PHONY : srv/fast

#=============================================================================
# Target rules for targets named srv1

# Build rule for target.
srv1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 srv1
.PHONY : srv1

# fast build rule for target.
srv1/fast:
	$(MAKE) -f src/intro/CMakeFiles/srv1.dir/build.make src/intro/CMakeFiles/srv1.dir/build
.PHONY : srv1/fast

#=============================================================================
# Target rules for targets named libfree

# Build rule for target.
libfree: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libfree
.PHONY : libfree

# fast build rule for target.
libfree/fast:
	$(MAKE) -f libfree/CMakeFiles/libfree.dir/build.make libfree/CMakeFiles/libfree.dir/build
.PHONY : libfree/fast

#=============================================================================
# Target rules for targets named libunp

# Build rule for target.
libunp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libunp
.PHONY : libunp

# fast build rule for target.
libunp/fast:
	$(MAKE) -f libs/CMakeFiles/libunp.dir/build.make libs/CMakeFiles/libunp.dir/build
.PHONY : libunp/fast

#=============================================================================
# Target rules for targets named tcpcli1

# Build rule for target.
tcpcli1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tcpcli1
.PHONY : tcpcli1

# fast build rule for target.
tcpcli1/fast:
	$(MAKE) -f src/tcpcliserv/CMakeFiles/tcpcli1.dir/build.make src/tcpcliserv/CMakeFiles/tcpcli1.dir/build
.PHONY : tcpcli1/fast

#=============================================================================
# Target rules for targets named tcpsrv1

# Build rule for target.
tcpsrv1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tcpsrv1
.PHONY : tcpsrv1

# fast build rule for target.
tcpsrv1/fast:
	$(MAKE) -f src/tcpcliserv/CMakeFiles/tcpsrv1.dir/build.make src/tcpcliserv/CMakeFiles/tcpsrv1.dir/build
.PHONY : tcpsrv1/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... main"
	@echo "... cli"
	@echo "... byteorder"
	@echo "... srv"
	@echo "... srv1"
	@echo "... libfree"
	@echo "... libunp"
	@echo "... tcpcli1"
	@echo "... tcpsrv1"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

